"""Zero-friction adoption helpers for Nornyx.

This module is intentionally local and deterministic. It does not call LLMs,
connectors, networks, GitHub, or production systems.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any
import re
import json


ADOPTION_LEVELS = ["observe", "lite", "standard", "team", "regulated", "enterprise"]
DEFAULT_EXCLUDES = [".env", "**/.env", "secrets/**", "generated/**", "node_modules/**", ".git/**"]
REQUIRED_NON_GOAL_SNIPPETS = [
    "live llm",
    "portal wizard",
    "fine-tuned model",
    "automatic remote git writes",
    "automatic approval",
    "production enforcement",
]
REQUIRED_FIRST_COMMANDS = {
    "python -m nornyx.cli adopt status --repo .",
    "python -m nornyx.cli adopt init-lite --project MyRepo --out nornyx.project.nyx",
}


@dataclass(frozen=True)
class AdoptionIssue:
    severity: str
    message: str


def slug_project_name(name: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_\-]+", "", name.strip().replace(" ", ""))
    return cleaned or "NornyxProject"


def detect_repo_signals(root: str | Path = ".") -> dict[str, Any]:
    path = Path(root)
    files = {p.name for p in path.iterdir()} if path.exists() else set()

    languages: list[str] = []
    if "pyproject.toml" in files or "requirements.txt" in files or any(path.glob("*.py")) or (path / "nornyx").exists():
        languages.append("python")
    if "package.json" in files:
        languages.append("javascript")
    if "go.mod" in files:
        languages.append("go")
    if "Cargo.toml" in files:
        languages.append("rust")

    test_commands: list[str] = []
    if (path / "tests").exists():
        test_commands.append("python -m pytest -q")
    if "package.json" in files:
        test_commands.append("npm test")

    docs_present = (path / "docs").exists() or "README.md" in files
    agents_present = "AGENTS.md" in files
    has_git = (path / ".git").exists()

    recommended_level = "lite"
    if (path / "docs" / "qa").exists() or (path / "docs" / "pmo").exists():
        recommended_level = "standard"
    if any((path / marker).exists() for marker in ["SECURITY.md", "docs/ADRs", "docs/RFCs"]):
        recommended_level = "standard"

    return {
        "root": str(path.resolve()),
        "languages": languages or ["unknown"],
        "test_commands": test_commands or ["python -m pytest -q"],
        "docs_present": docs_present,
        "agents_present": agents_present,
        "has_git": has_git,
        "recommended_level": recommended_level,
        "recommended_profile": "lite" if recommended_level == "lite" else "ai_coding",
        "recommended_first_commands": [
            "python -m nornyx.cli adopt status --repo .",
            "python -m nornyx.cli adopt init-lite --project <ProjectName> --out nornyx.project.nyx",
        ],
    }


def _yaml_list(items: list[str], indent: int = 6) -> str:
    prefix = " " * indent
    return "\n".join(f"{prefix}- {json.dumps(item)}" for item in items)


def render_lite_nyx(project_name: str, *, repo_root: str | Path = ".") -> str:
    project = slug_project_name(project_name)
    signals = detect_repo_signals(repo_root)
    tests = signals["test_commands"]

    include = ["README.md", "docs/**/*.md", "nornyx/**/*.py", "src/**/*.py", "tests/**/*.py", "examples/**/*.nyx"]
    excludes = DEFAULT_EXCLUDES

    return f'''# Generated by Nornyx Lite adoption. Review before accepting as source of truth.
nornyx: "0.1"
project:
  name: {project}
  category: ai_coding_lite
  description: "Minimal Nornyx Lite control file for safe AI-assisted development."

intents:
  - name: SafeAICoding
    goal: "Use Nornyx Lite to make AI-assisted development safer, clearer, and easier to review."
    success:
      - "Codex/Claude receive clear context, policy, and validation commands."
      - "Code changes produce basic evidence before handoff."

contexts:
  - name: RepoContext
    include:
{_yaml_list(include, indent=6)}
    exclude:
{_yaml_list(excludes, indent=6)}
    budget:
      max_tokens: 24000
      reserve_output_tokens: 4000

skills:
  - name: PatchBuilder
    purpose: "Produce small scoped patches."
    input: [TaskPacket, RepoContext]
    output: [PatchDiff]
  - name: TestRunner
    purpose: "Run focused local validation."
    input: [PatchDiff]
    output: [TestReport]

policies:
  - name: LiteSafeEditPolicy
    rules:
      - deny secrets_to_llm
      - deny production_write_without_approval
      - deny scope_expansion_without_triage
      - require tests_if_code_changed
      - require evidence_before_handoff

agents:
  - name: Builder
    role: "Implement small scoped AI-assisted changes."
    skills: [PatchBuilder, TestRunner]
    policy: LiteSafeEditPolicy

harnesses:
  - name: LiteFastHarness
    context: RepoContext
    flow:
      - agent: Builder
        action: implement_small_slice
      - tool: tests
        action: run_fast_validation
      - evidence: LiteEvidence
        action: summarize
    gate:
      - require: no_secret_exposure
      - require: tests_run_if_code_changed

traces:
  - name: LiteTrace
    capture:
      - file_change
      - test_command
      - evidence_created

evals:
  - name: LiteRegressionEval
    metrics:
      - tests_run == true
      - denied_paths_unchanged == true
      - evidence_present == true

evidence:
  required:
    - changed_files.txt
    - test_output.txt
    - risk_note.md
    - handoff.md

experimental:
  adoption:
    level: lite
    generated: true
    suggested_test_commands:
{_yaml_list(tests, indent=6)}
'''


def write_lite_nyx(project_name: str, out: str | Path, *, repo_root: str | Path = ".", force: bool = False) -> Path:
    path = Path(out)
    if path.exists() and not force:
        raise FileExistsError(f"{path} already exists. Use --force to overwrite.")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_lite_nyx(project_name, repo_root=repo_root), encoding="utf-8")
    return path


def adoption_status(root: str | Path = ".") -> dict[str, Any]:
    signals = detect_repo_signals(root)
    level = signals["recommended_level"]
    return {
        "level": level,
        "profile": signals["recommended_profile"],
        "signals": signals,
        "next_action": "init-lite" if not Path(root, "nornyx.project.nyx").exists() else "check",
        "recommended_command": (
            "python -m nornyx.cli adopt init-lite --project <ProjectName> --out nornyx.project.nyx"
            if not Path(root, "nornyx.project.nyx").exists()
            else "python -m nornyx.cli check nornyx.project.nyx"
        ),
    }


def adoption_summary(status: dict[str, Any]) -> str:
    signals = status.get("signals", {})
    languages = ",".join(signals.get("languages", []) if isinstance(signals, dict) else []) or "unknown"
    return (
        f"adoption_level={status.get('level', 'unknown')} "
        f"profile={status.get('profile', 'unknown')} "
        f"next={status.get('next_action', 'unknown')} "
        f"languages={languages}"
    )


def validate_adoption_pack(data: dict[str, Any]) -> list[AdoptionIssue]:
    issues: list[AdoptionIssue] = []
    if data.get("status") not in {"candidate", "stable"}:
        issues.append(AdoptionIssue("error", "status must be candidate or stable"))

    levels = data.get("adoption_levels")
    if not isinstance(levels, list) or not levels:
        issues.append(AdoptionIssue("error", "adoption_levels must be a non-empty list"))
    else:
        missing = [level for level in ["observe", "lite", "standard"] if level not in levels]
        if missing:
            issues.append(AdoptionIssue("error", f"missing required adoption levels: {missing}"))
        if levels[: len(ADOPTION_LEVELS)] != ADOPTION_LEVELS:
            issues.append(AdoptionIssue("warning", "adoption levels should follow observe/lite/standard/team/regulated/enterprise"))

    capabilities = data.get("capabilities")
    if not isinstance(capabilities, list) or not capabilities:
        issues.append(AdoptionIssue("error", "capabilities must be a non-empty list"))
    else:
        ids = set()
        for item in capabilities:
            if not isinstance(item, dict) or not item.get("id"):
                issues.append(AdoptionIssue("error", "each capability requires id"))
                continue
            if item["id"] in ids:
                issues.append(AdoptionIssue("error", f"duplicate capability: {item['id']}"))
            ids.add(item["id"])
            if item.get("status") not in {"candidate", "roadmap"}:
                issues.append(AdoptionIssue("error", f"capability {item['id']} must be candidate or roadmap"))
            if not isinstance(item.get("safe_now"), bool):
                issues.append(AdoptionIssue("error", f"capability {item['id']}.safe_now must be boolean"))
            if item["id"] == "upgrade_preview" and item.get("safe_now") is True:
                issues.append(AdoptionIssue("error", "upgrade_preview cannot be safe_now"))
        for required in ["repo_status", "init_lite", "fast_quality_hint"]:
            if required not in ids:
                issues.append(AdoptionIssue("warning", f"recommended capability missing: {required}"))

    non_goals = data.get("non_goals")
    if not isinstance(non_goals, list) or not all(isinstance(item, str) and item.strip() for item in non_goals):
        issues.append(AdoptionIssue("error", "non_goals must be a non-empty string list"))
    else:
        text = " ".join(non_goals).lower()
        for snippet in REQUIRED_NON_GOAL_SNIPPETS:
            if snippet not in text:
                issues.append(AdoptionIssue("error", f"non_goals must block {snippet!r}"))

    first_commands = data.get("first_commands")
    if not isinstance(first_commands, list) or not all(isinstance(item, str) and item.strip() for item in first_commands):
        issues.append(AdoptionIssue("error", "first_commands must be a non-empty string list"))
    else:
        missing_commands = sorted(REQUIRED_FIRST_COMMANDS - set(first_commands))
        if missing_commands:
            issues.append(AdoptionIssue("error", f"first_commands missing: {missing_commands}"))

    return issues
