from __future__ import annotations

from pathlib import Path
from typing import Any
import hashlib
import json
import re
import yaml


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    # Force LF so generated artifacts are byte-identical across platforms
    # (otherwise Windows writes CRLF and drift-baseline hashes diverge).
    path.write_text(content, encoding="utf-8", newline="\n")


def _safe_segment(value: Any, fallback: str) -> str:
    raw = str(value or fallback).strip()
    safe = re.sub(r"[^A-Za-z0-9_.-]+", "-", raw).strip(".-")
    return safe or fallback


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _artifact_paths(out: Path, generated: list[Path]) -> list[str]:
    return sorted(path.relative_to(out).as_posix() for path in generated)


def _artifact_hashes(out: Path, generated: list[Path]) -> list[dict[str, str]]:
    return [
        {"path": path.relative_to(out).as_posix(), "sha256": _sha256(path)}
        for path in sorted(generated, key=lambda item: item.relative_to(out).as_posix())
    ]


def _append_field(lines: list[str], label: str, value: Any) -> None:
    if value in (None, "", []):
        return
    lines.append(f"### {label}\n\n")
    if isinstance(value, list):
        for item in value:
            lines.append(f"- {item}\n")
    elif isinstance(value, dict):
        lines.append("```yaml\n")
        lines.append(yaml.safe_dump(value, sort_keys=False))
        lines.append("```\n")
    else:
        lines.append(f"{value}\n")
    lines.append("\n")


def _task_packet(goal: dict[str, Any]) -> str:
    gid = goal.get("id", "GOAL-UNKNOWN")
    title = goal.get("title", goal.get("goal", "Untitled goal"))
    lines = [
        f"# {gid} — {title}\n\n",
        "Generated by Nornyx. Execute this as a bounded, evidence-backed task packet.\n\n",
    ]
    for label, key in [
        ("Phase", "phase"),
        ("Goal", "goal"),
        ("Scope", "scope"),
        ("Non Goals", "non_goals"),
        ("Validation", "validation"),
        ("Evidence", "evidence"),
        ("Approval", "approval"),
        ("Stop Rules", "stop_rules"),
    ]:
        _append_field(lines, label, goal.get(key))
    return "".join(lines)


def generate_artifacts(doc: dict[str, Any], out_dir: str | Path) -> list[Path]:
    """Generate compatibility artifacts from a .nyx document.

    This proves the v0.1 strategy: Nornyx is the source of truth; existing
    AI-engineering files are generated outputs.
    """
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    project = doc.get("project", {})
    project_name = project.get("name", "UnnamedProject") if isinstance(project, dict) else "UnnamedProject"
    generated: list[Path] = []

    agents_md = [f"# AGENTS.md generated by Nornyx for {project_name}\n"]
    agents_md.append("This file is generated. Edit the `.nyx` source instead.\n")
    agents_md.append("## Project intent\n")
    for intent in doc.get("intents", []) or []:
        agents_md.append(f"- **{intent.get('name')}**: {intent.get('goal', '')}\n")
    agents_md.append("\n## Agent profiles\n")
    for agent in doc.get("agents", []) or []:
        agents_md.append(f"### {agent.get('name')}\n")
        agents_md.append(f"Role: {agent.get('role', '')}\n\n")
        if agent.get("skills"):
            agents_md.append("Skills: " + ", ".join(agent.get("skills", [])) + "\n\n")
        if agent.get("policy"):
            agents_md.append(f"Policy: {agent.get('policy')}\n\n")
    p = out / "AGENTS.md"
    _write(p, "".join(agents_md))
    generated.append(p)

    for skill in doc.get("skills", []) or []:
        name = skill.get("name", "UnnamedSkill")
        text = (
            f"# {name}\n\n"
            "Generated by Nornyx.\n\n"
            f"Purpose: {skill.get('purpose', '')}\n\n"
            f"Inputs: {skill.get('input', [])}\n\n"
            f"Outputs: {skill.get('output', [])}\n"
        )
        p = out / "skills" / _safe_segment(name, "UnnamedSkill") / "README.md"
        _write(p, text)
        generated.append(p)

    mapping_outputs = {
        "context.yaml": {"contexts": doc.get("contexts", [])},
        "harness.yaml": {"harnesses": doc.get("harnesses", [])},
        "policy.yaml": {"policies": doc.get("policies", [])},
        "evals.yaml": {"evals": doc.get("evals", [])},
        "trace.yaml": {"traces": doc.get("traces", [])},
        "goals.yaml": {"goals": doc.get("goals", [])},
    }
    for filename, payload in mapping_outputs.items():
        p = out / filename
        _write(p, yaml.safe_dump(payload, sort_keys=False))
        generated.append(p)

    goals = doc.get("goals", []) or []
    if goals:
        for index, goal in enumerate(goals, start=1):
            if isinstance(goal, dict):
                gid = _safe_segment(goal.get("id"), f"GOAL-{index:03d}")
                p = out / "task_packets" / f"{gid}.md"
                _write(p, _task_packet(goal))
                generated.append(p)

        lines = [
            "# Goal Ledger\n\n",
            "Generated by Nornyx. Each phase can be executed as a bounded goal.\n\n",
        ]
        for goal in goals:
            if isinstance(goal, dict):
                title = goal.get("title", goal.get("goal", "Untitled"))
                lines.append(f"## {goal.get('id', '<unnamed>')} — {title}\n\n")
                lines.append(f"Phase: {goal.get('phase', '')}\n\n")
                lines.append(f"Goal: {goal.get('goal', '')}\n\n")
                if goal.get("validation"):
                    lines.append("Validation:\n")
                    for item in goal.get("validation", []) or []:
                        lines.append(f"- {item}\n")
                    lines.append("\n")
                if goal.get("evidence"):
                    lines.append(f"Evidence: {goal.get('evidence')}\n\n")
        p = out / "goal_ledger.md"
        _write(p, "".join(lines))
        generated.append(p)

    evidence = doc.get("evidence", {})
    p = out / "evidence_contract.md"
    lines = ["# Evidence Contract\n\n", "Generated by Nornyx.\n\n"]
    if isinstance(evidence, dict):
        for item in evidence.get("required", []) or []:
            lines.append(f"- {item}\n")
    _write(p, "".join(lines))
    generated.append(p)

    manifest = {
        "schema": "nornyx.generation_manifest.v0.1",
        "project": project_name,
        "generated_by": "nornyx v0.1 scaffold",
        "source_blocks": sorted(str(key) for key in doc.keys()),
        "artifact_count": len(generated),
        "artifacts": _artifact_paths(out, generated),
        "artifact_hashes": _artifact_hashes(out, generated),
    }
    p = out / "nornyx_generation_manifest.json"
    _write(p, json.dumps(manifest, indent=2))
    generated.append(p)
    return generated
